[package]
name = "pid-checker"
version = "2.0.0"
edition = "2021"

[profile.release]
opt-level = 3
lto = true
strip = true

[profile.dev]
opt-level = 0

[[bin]]
name = "pidchecker"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.2"
dotenv = "0.15.0"
tokio = { version = "1.18.2", features = ["rt-multi-thread", "macros"] }
tracing = "0.1.34"
tracing-subscriber = "0.3.11"
